name: tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
  pull_request:
    branches_ignore: []

jobs:
  Dry_Run_and_Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://snakemake/snakemake:v5.24.2
    - name: Dry run visium_hd with test data
      run: |
        docker run -v $PWD:/opt2 snakemake/snakemake:v5.24.2 \
        /opt2/space-seek run --input \
        /opt2/.tests/fastqs/LIB_01_WT/LIB_WT_01_S1_L001_R1_001.fastq.gz /opt2/.tests/fastqs/LIB_01_WT/LIB_01_WT_S1_L001_R2_001.fastq.gz \
        /opt2/.tests/fastqs/LIB_02_WT/LIB_WT_02_S2_L001_R1_001.fastq.gz /opt2/.tests/fastqs/LIB_02_WT/LIB_02_WT_S2_L001_R2_001.fastq.gz \
        /opt2/.tests/fastqs/LIB_03_KO/LIB_KO_03_S3_L001_R1_001.fastq.gz /opt2/.tests/fastqs/LIB_03_KO/LIB_03_KO_S3_L001_R2_001.fastq.gz \
        /opt2/.tests/fastqs/LIB_04_KO/LIB_KO_04_S4_L001_R1_001.fastq.gz /opt2/.tests/fastqs/LIB_04_KO/LIB_04_KO_S4_L001_R2_001.fastq.gz \
        --output /opt2/output --sample-sheet /opt2/.tests/sample_sheet.csv --genome hg38_2024 --assay visium_hd \
        --mode local --dry-run
    - name: Dry run visium_hd_3_prime with test data
      run: |
        docker run -v $PWD:/opt2 snakemake/snakemake:v5.24.2 \
        /opt2/space-seek run --input \
        /opt2/.tests/fastqs/LIB_01_WT/LIB_WT_01_S1_L001_R1_001.fastq.gz /opt2/.tests/fastqs/LIB_01_WT/LIB_01_WT_S1_L001_R2_001.fastq.gz \
        /opt2/.tests/fastqs/LIB_02_WT/LIB_WT_02_S2_L001_R1_001.fastq.gz /opt2/.tests/fastqs/LIB_02_WT/LIB_02_WT_S2_L001_R2_001.fastq.gz \
        /opt2/.tests/fastqs/LIB_03_KO/LIB_KO_03_S3_L001_R1_001.fastq.gz /opt2/.tests/fastqs/LIB_03_KO/LIB_03_KO_S3_L001_R2_001.fastq.gz \
        /opt2/.tests/fastqs/LIB_04_KO/LIB_KO_04_S4_L001_R1_001.fastq.gz /opt2/.tests/fastqs/LIB_04_KO/LIB_04_KO_S4_L001_R2_001.fastq.gz \
        --output /opt2/output --sample-sheet /opt2/.tests/sample_sheet.csv --genome hg38_2024 --assay visium_hd_3_prime \
        --mode local --dry-run
    - name: View the pipeline config file
      run: |
        echo "Generated config file for pipeline...." && cat $PWD/output/config.json
    - name: Lint Workflow
      continue-on-error: true
      run: |
        docker run -v $PWD:/opt2 snakemake/snakemake:v5.24.2 snakemake --lint -s /opt2/output/workflow/Snakefile -d /opt2/output || \
        echo 'There may have been a few warnings or errors. Please read through the log to determine if its harmless.'
